
  import { defineConfig } from 'vite';
  import react from '@vitejs/plugin-react-swc';
  import wasm from 'vite-plugin-wasm';
  import topLevelAwait from 'vite-plugin-top-level-await';
  import path from 'path';

  export default defineConfig({
    plugins: [react(), wasm(), topLevelAwait()],
    resolve: {
      extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
      /** One copy of React — avoids "Invalid hook call" / useState from null in dev. */
      dedupe: ['react', 'react-dom', 'scheduler'],
      alias: {
        buffer: path.resolve(__dirname, 'node_modules/buffer'),
        react: path.resolve(__dirname, 'node_modules/react'),
        'react-dom': path.resolve(__dirname, 'node_modules/react-dom'),
        'wavesurfer.js@7.8.10': 'wavesurfer.js',
        'vaul@1.1.2': 'vaul',
        'sonner@2.0.3': 'sonner',
        'recharts@2.15.2': 'recharts',
        'react-resizable-panels@2.1.7': 'react-resizable-panels',
        'react-hook-form@7.55.0': 'react-hook-form',
        'react-easy-crop@5.0.8': 'react-easy-crop',
        'react-day-picker@8.10.1': 'react-day-picker',
        'lucide-react@0.487.0': 'lucide-react',
        'input-otp@1.4.2': 'input-otp',
        'hono@4.6.14': 'hono',
        'hono@4': 'hono',
        'figma:asset/f457350c3280dabb6ea90d22b03423bcf23f5ad9.png': path.resolve(__dirname, './src/assets/f457350c3280dabb6ea90d22b03423bcf23f5ad9.png'),
        'figma:asset/762fa3b0c4bc468cb3c0661e6181aee92a01370d.png': path.resolve(__dirname, './src/assets/762fa3b0c4bc468cb3c0661e6181aee92a01370d.png'),
        'figma:asset/5bbfb6c934162456ce6c992c152322cee414939e.png': path.resolve(__dirname, './src/assets/5bbfb6c934162456ce6c992c152322cee414939e.png'),
        'figma:asset/44d55a83c8fdb84cc42417330166e084e82bbcea.png': path.resolve(__dirname, './src/assets/44d55a83c8fdb84cc42417330166e084e82bbcea.png'),
        'embla-carousel-react@8.6.0': 'embla-carousel-react',
        'cmdk@1.1.1': 'cmdk',
        'class-variance-authority@0.7.1': 'class-variance-authority',
        '@radix-ui/react-tooltip@1.1.8': '@radix-ui/react-tooltip',
        '@radix-ui/react-toggle@1.1.2': '@radix-ui/react-toggle',
        '@radix-ui/react-toggle-group@1.1.2': '@radix-ui/react-toggle-group',
        '@radix-ui/react-tabs@1.1.3': '@radix-ui/react-tabs',
        '@radix-ui/react-switch@1.1.3': '@radix-ui/react-switch',
        '@radix-ui/react-slot@1.1.2': '@radix-ui/react-slot',
        '@radix-ui/react-slider@1.2.3': '@radix-ui/react-slider',
        '@radix-ui/react-separator@1.1.2': '@radix-ui/react-separator',
        '@radix-ui/react-select@2.1.6': '@radix-ui/react-select',
        '@radix-ui/react-scroll-area@1.2.3': '@radix-ui/react-scroll-area',
        '@radix-ui/react-radio-group@1.2.3': '@radix-ui/react-radio-group',
        '@radix-ui/react-popover@1.1.6': '@radix-ui/react-popover',
        '@radix-ui/react-navigation-menu@1.2.5': '@radix-ui/react-navigation-menu',
        '@radix-ui/react-menubar@1.1.6': '@radix-ui/react-menubar',
        '@radix-ui/react-label@2.1.2': '@radix-ui/react-label',
        '@radix-ui/react-hover-card@1.1.6': '@radix-ui/react-hover-card',
        '@radix-ui/react-dropdown-menu@2.1.6': '@radix-ui/react-dropdown-menu',
        '@radix-ui/react-dialog@1.1.6': '@radix-ui/react-dialog',
        '@radix-ui/react-context-menu@2.2.6': '@radix-ui/react-context-menu',
        '@radix-ui/react-collapsible@1.1.3': '@radix-ui/react-collapsible',
        '@radix-ui/react-checkbox@1.1.4': '@radix-ui/react-checkbox',
        '@radix-ui/react-avatar@1.1.3': '@radix-ui/react-avatar',
        '@radix-ui/react-aspect-ratio@1.1.2': '@radix-ui/react-aspect-ratio',
        '@radix-ui/react-alert-dialog@1.1.6': '@radix-ui/react-alert-dialog',
        '@radix-ui/react-accordion@1.2.3': '@radix-ui/react-accordion',
        '@': path.resolve(__dirname, './src'),
      },
    },
    publicDir: 'public',
    optimizeDeps: {
      include: [
        'react',
        'react-dom',
        'scheduler',
        'mammoth',
        'pdfjs-dist',
        'buffer',
        'cfb',
      ],
      exclude: ['@jsquash/webp'],
    },
    build: {
      target: 'esnext',
      outDir: 'build',
    },
    server: {
      port: 3000,
      open: true,
    },
  });